spring:
  profiles:
    active:
      -  dog
      -  EN
      -  prod

com:
  username: ylmUserName
  password: YmlPassword
  jdbcurl: YmlUrl


---

spring:
  profiles: prod
com:
  username: Yolo
  password: yooolloooo
  jdbcurl: jomama